// Copies the compiled ABI and bytecode into the web app as a typed module.
const fs = require("fs");
const path = require("path");

const artifact = require("../artifacts/contracts/ReleaseBond.sol/ReleaseBond.json");
const out = path.join(__dirname, "..", "..", "web", "src", "lib", "chain", "releaseBondArtifact.ts");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `// Generated by contracts/scripts/export-abi.js. Do not edit by hand.\n` +
    `export const releaseBondAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n` +
    `export const releaseBondBytecode = ${JSON.stringify(artifact.bytecode)} as \`0x\${string}\`;\n`,
);
console.log(`exported ABI (${artifact.abi.length} entries) to ${path.relative(process.cwd(), out)}`);
